version: "3"

services:
  pyanoled:
    image: pyanoled:latest
    container_name: pyanoled
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint:
      - /usr/bin/bash
      - docker/entrypoint.sh
    volumes:
      - ".:/opt/app"